// $g++ xxdtest.cpp ../common/general.cpp -I../common -o xxdtest -lfltk_images -lfltk -lX11 -lXtst -Os -s  -std=c++20 -lXext -lXft -lXrender -lXcursor -lXinerama -lXfixes -lfontconfig -lfreetype -lz -lm -ldl -lpthread -lstdc++ -Os -w -Wfatal-errors -DNDEBUG -lasound  -lXss -lXi -ludev -lpng -ljpeg -lz


#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_PNG_Image.H>
#include "favicon.hpp"   // generated by xxd -i

int main() {
    Fl_Window win(200,200,"Button with Favicon");

    // Construct image directly from embedded PNG data
    Fl_PNG_Image icon("favicon.png", favicon_png, favicon_png_len);

    Fl_Button btn(50,50,30,30,"");
btn.labelsize(0);
    // Scale image to button size
int target_w = btn.w();
int target_h = btn.h();
double aspect = (double)icon.w() / icon.h();

if ((double)target_w / target_h > aspect) {
    target_w = (int)(target_h * aspect);
} else {
    target_h = (int)(target_w / aspect);
}

Fl_Image *scaled = icon.copy(target_w, target_h);
btn.image(scaled);
btn.align(FL_ALIGN_CENTER | FL_ALIGN_INSIDE);

    win.end();
    win.show();
    return Fl::run();
}
