name: Correr cwin workflow

on:
  workflow_dispatch:

jobs:
  run-cwin:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Executar bot
        run: ./cwin
        working-directory: ./crbot
        env:
          MEXC_API_KEY: ${{ secrets.MEXC_API_KEY }}
          MEXC_API_SECRET: ${{ secrets.MEXC_API_SECRET }}
          WB_KEY: ${{ secrets.WB_KEY }}
          WB_SECRET: ${{ secrets.WB_SECRET }}
          CG_KEY: ${{ secrets.CG_KEY }}