name: Correr cwin workflow

on:
  workflow_dispatch:

jobs:
  run-cwin:
    runs-on: ubuntu-24.04

    steps:
      - name: Baixar apenas o executavel cwin
        run: |
          mkdir -p crbot
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3.raw" \
               -L "https://api.github.com/repos/${{ github.repository }}/contents/crbot/cwin" \
               -o crbot/cwin
          chmod +x crbot/cwin

      - name: Executar bot
        run: ./cwin
        working-directory: ./crbot
        env:
          MEXC_API_KEY: ${{ secrets.MEXC_API_KEY }}
          MEXC_API_SECRET: ${{ secrets.MEXC_API_SECRET }}
          WB_KEY: ${{ secrets.WB_KEY }}
          WB_SECRET: ${{ secrets.WB_SECRET }}
          CG_KEY: ${{ secrets.CG_KEY }}